/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.table.DefaultTableModel;
import database.ConteudoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaConteudos extends javax.swing.JFrame {

    ConteudoDAO conteudodao = new ConteudoDAO();
    /**
     * Creates new form TelaConteudos
     */
    public TelaConteudos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        conteudosTabela = new javax.swing.JTable();
        disciplinaLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        conteudoTextPane = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        disciplinaTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        anotacaoTextPane = new javax.swing.JTextArea();
        descricaoLabel = new javax.swing.JLabel();
        atividadeLabel = new javax.swing.JLabel();
        escalaSlider = new javax.swing.JSlider();
        disciplinaLabel1 = new javax.swing.JLabel();
        escalaLabel = new javax.swing.JLabel();
        revisarLabel = new javax.swing.JLabel();
        reviseiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        conteudosTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        conteudosTabela.setRowHeight(30);
        conteudosTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conteudosTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(conteudosTabela);

        disciplinaLabel.setText("Disciplina");

        jScrollPane6.setViewportView(conteudoTextPane);

        jScrollPane7.setViewportView(disciplinaTextPane);

        anotacaoTextPane.setColumns(20);
        anotacaoTextPane.setRows(5);
        jScrollPane2.setViewportView(anotacaoTextPane);

        descricaoLabel.setText("Anotações");

        atividadeLabel.setText("Conteúdo");

        escalaSlider.setMaximum(10);
        escalaSlider.setToolTipText("");
        escalaSlider.setValue(5);
        escalaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                escalaSliderStateChanged(evt);
            }
        });
        escalaSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escalaSliderMouseClicked(evt);
            }
        });

        disciplinaLabel1.setText("O quanto você aprendeu sobre esse conteúdo?");

        revisarLabel.setText("Revisar!");

        reviseiButton.setText("Revisei!");
        reviseiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviseiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disciplinaLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(atividadeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reviseiButton)
                                        .addComponent(disciplinaLabel1)
                                        .addComponent(escalaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(descricaoLabel))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(escalaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(revisarLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atividadeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disciplinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disciplinaLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escalaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escalaLabel)
                        .addGap(14, 14, 14)
                        .addComponent(revisarLabel)
                        .addGap(3, 3, 3)
                        .addComponent(reviseiButton)
                        .addGap(18, 18, 18)
                        .addComponent(descricaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escalaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_escalaSliderStateChanged
        escalaLabel.setText(Integer.toString(escalaSlider.getValue()));
    }//GEN-LAST:event_escalaSliderStateChanged

    private void escalaSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escalaSliderMouseClicked
        escalaLabel.setText(Integer.toString(escalaSlider.getValue()));
    }//GEN-LAST:event_escalaSliderMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] col = {"Conteúdo", "Disciplina", "Anotações", "Aprendizado"};
        
        TelaAtividades tela = new TelaAtividades();
        DefaultTableModel model = (DefaultTableModel) conteudosTabela.getModel();
        conteudosTabela.setModel(model);
        model.setDataVector(conteudodao.formatarTabela(), col);
        conteudodao.carregarMetas();
        
        if (conteudosTabela.getColumnModel().getColumnCount() > 0) {
            conteudosTabela.getColumnModel().getColumn(0).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(1).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(3).setMinWidth(50);
            conteudosTabela.getColumnModel().getColumn(3).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(3).setMaxWidth(80);
        }

    }//GEN-LAST:event_formWindowOpened

    private void conteudosTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conteudosTabelaMouseClicked
        int index = conteudosTabela.getSelectedRow();
        conteudoTextPane.setText(ConteudoDAO.conteudos.get(index).getNome());
        disciplinaTextPane.setText(ConteudoDAO.conteudos.get(index).getDisciplina().getNome());
        anotacaoTextPane.setText(ConteudoDAO.conteudos.get(index).getAnotacao());
        escalaLabel.setText(Integer.toString(ConteudoDAO.conteudos.get(index).getAprendizado()));
        escalaSlider.setValue(ConteudoDAO.conteudos.get(index).getAprendizado());
        if(ConteudoDAO.conteudos.get(index).getMeta() == 0){
            revisarLabel.setText("Parabéns! Você cumpriu a sua meta!");
        }else{
            revisarLabel.setText("Revisar " + Integer.toString(ConteudoDAO.conteudos.get(index).getMeta()) + " vezes!");
        }
    }//GEN-LAST:event_conteudosTabelaMouseClicked

    private void reviseiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviseiButtonActionPerformed
        int revisoes = ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getMeta() - 1;
        conteudodao.atualizarMetas(revisoes, conteudosTabela.getSelectedRow());
        if(revisoes == 0){
            JOptionPane.showMessageDialog(null, "Parabéns! Você cumpriu a sua meta!", "Parabéns!", 1);
            revisarLabel.setText("Parabéns! Você cumpriu a sua meta de revisões!");
        }else{
            revisarLabel.setText("Revisar " + Integer.toString(ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getMeta()));
        }
    }//GEN-LAST:event_reviseiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConteudos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anotacaoTextPane;
    private javax.swing.JLabel atividadeLabel;
    private javax.swing.JTextPane conteudoTextPane;
    private javax.swing.JTable conteudosTabela;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JLabel disciplinaLabel;
    private javax.swing.JLabel disciplinaLabel1;
    private javax.swing.JTextPane disciplinaTextPane;
    private javax.swing.JLabel escalaLabel;
    private javax.swing.JSlider escalaSlider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel revisarLabel;
    private javax.swing.JButton reviseiButton;
    // End of variables declaration//GEN-END:variables
}
