package views;

import database.ConexaoDAO;
import database.LoginDAO;
import database.EstudanteDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import models.Estudante;

public class TelaLogin extends javax.swing.JFrame {
    private ConexaoDAO conexao = new ConexaoDAO();
    private EstudanteDAO estudante = new EstudanteDAO();
    private LoginDAO conexaoLogin = new LoginDAO(conexao);
    
    //DADOS DE TESTE DE LOGIN:
    //Email: admin@email.com
    //Senha: admin123
    
    
    public TelaLogin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        cadastrese = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(621, 674));
        getContentPane().setLayout(null);

        emailTextField.setForeground(new java.awt.Color(153, 153, 153));
        emailTextField.setText("  digite o seu e-mail...");
        emailTextField.setBorder(null);
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(170, 310, 270, 14);

        senhaPasswordField.setBorder(null);
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(170, 394, 270, 20);

        cadastrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastreseMouseClicked(evt);
            }
        });
        getContentPane().add(cadastrese);
        cadastrese.setBounds(210, 450, 70, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grupo 50.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 30, 490, 100);

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(340, 450, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoStudyItYourself1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 440, 160, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 620, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
        if(emailTextField.getText().equals("  digite o seu e-mail...")){
            emailTextField.setText("");
            emailTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed

    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void cadastreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastreseMouseClicked
        dispose();
        TelaCadastro cadastro = new TelaCadastro();
        cadastro.show();
    }//GEN-LAST:event_cadastreseMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        if(conexaoLogin.fazerLogin(emailTextField.getText(), senhaPasswordField.getText())){
            //ir para tela inicial
            Estudante e = estudante.criarObjetoEstudante(emailTextField.getText());
            System.out.println("Seja bem-vindo(a), " + e.getNome() + "!");
            estudante.carregarInformacoes(e.getId());
            dispose();
            TelaInicial tela = new TelaInicial();
            tela.show();
        }
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrese;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
