package views;

import java.awt.Color;
import javax.swing.JOptionPane;
import database.CadastroDAO;
import database.ConexaoDAO;
import models.Estudante;

public class TelaCadastro extends javax.swing.JFrame {
    ConexaoDAO conexao = new ConexaoDAO();

    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        senhaConfirmaPasswordField = new javax.swing.JPasswordField();
        cadastroLabel = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        cadastrese = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(805, 527));
        getContentPane().setLayout(null);

        nomeTextField.setForeground(new java.awt.Color(153, 153, 153));
        nomeTextField.setText("  digite seu nome...");
        nomeTextField.setBorder(null);
        nomeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeTextFieldMouseClicked(evt);
            }
        });
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField);
        nomeTextField.setBounds(330, 90, 250, 14);

        emailTextField.setForeground(new java.awt.Color(153, 153, 153));
        emailTextField.setText("  digite o seu e-mail...");
        emailTextField.setBorder(null);
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(330, 140, 250, 14);

        senhaPasswordField.setBorder(null);
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(330, 190, 250, 14);

        senhaConfirmaPasswordField.setBorder(null);
        senhaConfirmaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaConfirmaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaConfirmaPasswordField);
        senhaConfirmaPasswordField.setBounds(330, 240, 260, 10);

        cadastroLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        cadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroLabel.setText("Cadastre-se!");
        getContentPane().add(cadastroLabel);
        cadastroLabel.setBounds(380, 10, 190, 40);

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(340, 280, 90, 30);

        cadastrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastreseMouseClicked(evt);
            }
        });
        getContentPane().add(cadastrese);
        cadastrese.setBounds(480, 280, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/janela cadastro nova.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 680, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void nomeTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTextFieldMouseClicked
        if(nomeTextField.getText().equals("  digite seu nome...")){
            nomeTextField.setText("");
            nomeTextField.setForeground(Color.black);
       }
    }//GEN-LAST:event_nomeTextFieldMouseClicked

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
        if(emailTextField.getText().equals("  digite o seu e-mail...")){
            emailTextField.setText("");
            emailTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        dispose();
        TelaLogin login = new TelaLogin();
        login.show();
    }//GEN-LAST:event_loginMouseClicked

    private void cadastreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastreseMouseClicked
        CadastroDAO cadastro = new CadastroDAO(conexao);
        boolean senhasIguais = cadastro.confirmarSenhasIguais(senhaPasswordField.getText(), senhaConfirmaPasswordField.getText());
        if(senhasIguais){
            if(cadastro.cadastrar(nomeTextField.getText(), emailTextField.getText(), senhaPasswordField.getText())){
                dispose();
                TelaLogin login = new TelaLogin();
                login.show();
            }
        }else{
            JOptionPane.showMessageDialog(null, "As senhas não são iguais!", "ERRO!", 0);
        }
    }//GEN-LAST:event_cadastreseMouseClicked

    private void senhaConfirmaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaConfirmaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaConfirmaPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrese;
    private javax.swing.JLabel cadastroLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel login;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JPasswordField senhaConfirmaPasswordField;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
