/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import database.AtividadeDAO;
import database.ConexaoDAO;
import database.DisciplinaDAO;
import database.EstudanteDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Atividade;

/**
 *
 * @author andre
 */
public class TelaNovaAtividade extends javax.swing.JFrame {
    
    Atividade atividade = new Atividade();
    AtividadeDAO atividadedao = new AtividadeDAO();

    /**
     * Creates new form TelaNovaAtividade
     */
    public TelaNovaAtividade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        concluidaCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        disciplinasComboBox = new javax.swing.JComboBox<>();
        notaTextField = new javax.swing.JTextField();
        diaTextField = new javax.swing.JTextField();
        mesTextField = new javax.swing.JTextField();
        anoTextField = new javax.swing.JTextField();
        diaConclusaoTextField = new javax.swing.JTextField();
        mesConclusaoTextField = new javax.swing.JTextField();
        anoConclusaoTextField = new javax.swing.JTextField();
        atividadeTextField = new javax.swing.JTextField();
        nova = new javax.swing.JLabel();
        notaMaxTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1303, 738));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        concluidaCheckBox.setText("Concluída");
        concluidaCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                concluidaCheckBoxStateChanged(evt);
            }
        });
        concluidaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluidaCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(concluidaCheckBox);
        concluidaCheckBox.setBounds(550, 630, 71, 23);

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        descricaoTextArea.setBorder(null);
        jScrollPane2.setViewportView(descricaoTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 410, 700, 200);

        disciplinasComboBox.setMaximumSize(new java.awt.Dimension(79, 20));
        disciplinasComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                disciplinasComboBoxItemStateChanged(evt);
            }
        });
        disciplinasComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disciplinasComboBoxMouseClicked(evt);
            }
        });
        getContentPane().add(disciplinasComboBox);
        disciplinasComboBox.setBounds(300, 290, 190, 40);

        notaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaTextField.setText("0.0");
        notaTextField.setBorder(null);
        notaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(notaTextField);
        notaTextField.setBounds(801, 672, 40, 20);

        diaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaTextField.setBorder(null);
        diaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(diaTextField);
        diaTextField.setBounds(818, 204, 40, 20);

        mesTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mesTextField.setBorder(null);
        mesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(mesTextField);
        mesTextField.setBounds(888, 207, 40, 20);

        anoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anoTextField.setBorder(null);
        getContentPane().add(anoTextField);
        anoTextField.setBounds(958, 207, 40, 20);

        diaConclusaoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaConclusaoTextField.setBorder(null);
        diaConclusaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaConclusaoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(diaConclusaoTextField);
        diaConclusaoTextField.setBounds(494, 670, 40, 20);

        mesConclusaoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mesConclusaoTextField.setBorder(null);
        getContentPane().add(mesConclusaoTextField);
        mesConclusaoTextField.setBounds(564, 670, 40, 20);

        anoConclusaoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anoConclusaoTextField.setBorder(null);
        getContentPane().add(anoConclusaoTextField);
        anoConclusaoTextField.setBounds(634, 673, 40, 14);

        atividadeTextField.setBorder(null);
        getContentPane().add(atividadeTextField);
        atividadeTextField.setBounds(320, 206, 390, 20);

        nova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novaMouseClicked(evt);
            }
        });
        getContentPane().add(nova);
        nova.setBounds(560, 300, 100, 20);

        notaMaxTextField.setBorder(null);
        getContentPane().add(notaMaxTextField);
        notaMaxTextField.setBounds(870, 300, 80, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nota_novaatividade.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 645, 70, 60);

        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(930, 670, 90, 30);

        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(290, 670, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nova atividade.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1310, 740);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void concluidaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluidaCheckBoxActionPerformed

    }//GEN-LAST:event_concluidaCheckBoxActionPerformed

    private void disciplinasComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disciplinasComboBoxMouseClicked
    }//GEN-LAST:event_disciplinasComboBoxMouseClicked

    private void disciplinasComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_disciplinasComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinasComboBoxItemStateChanged

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        disciplinasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarComboBox()));

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void notaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaTextFieldActionPerformed

    private void concluidaCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_concluidaCheckBoxStateChanged
    }//GEN-LAST:event_concluidaCheckBoxStateChanged

    private void diaConclusaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaConclusaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaConclusaoTextFieldActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        disciplinasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarComboBox()));
    }//GEN-LAST:event_formWindowGainedFocus

    private void novaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novaMouseClicked
        TelaDisciplinas tela = new TelaDisciplinas();
        tela.show();
    }//GEN-LAST:event_novaMouseClicked

    private void diaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTextFieldActionPerformed

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        String nome = atividadeTextField.getText();
        String descricao = descricaoTextArea.getText();
        int idDisciplina = 0;
        String querySelect = "SELECT id FROM DISCIPLINA WHERE nome = ? AND fk_estudante = ?";
        ArrayList<Object> dadosSelect = new ArrayList<>();
        dadosSelect.add(disciplinasComboBox.getSelectedItem().toString());
        dadosSelect.add(EstudanteDAO.estudante.getId());
        ConexaoDAO conexao = new ConexaoDAO();
        conexao.getConnection();
        ResultSet rs = conexao.Select(querySelect, dadosSelect);
        try{
            if(rs!= null && rs.next())
                idDisciplina = rs.getInt(1);
        }catch(SQLException ex){
            Logger.getLogger(ConexaoDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        conexao.closeConnection();
        double notaMaxima = Double.parseDouble(notaMaxTextField.getText());
        LocalDate p = LocalDate.of(Integer.parseInt(anoTextField.getText()),
                Integer.parseInt(mesTextField.getText()),
                Integer.parseInt(diaTextField.getText()));
        LocalDate prazo = p.withDayOfMonth(Integer.parseInt(diaTextField.getText()));
        boolean concluida = concluidaCheckBox.isSelected();
        LocalDate dataConclusao;
        double nota;
        if(concluida){
            dataConclusao = LocalDate.of(Integer.parseInt(anoConclusaoTextField.getText()),
                Integer.parseInt(mesConclusaoTextField.getText()),
                Integer.parseInt(diaConclusaoTextField.getText()));
            nota = Double.parseDouble(notaTextField.getText());

        }else{
            dataConclusao = LocalDate.of(1970, 1, 1);
            nota = -1;
        }
        
        int idEstudante = EstudanteDAO.estudante.getId();

        atividadedao.cadastrarAtividade(nome, descricao, idDisciplina, nota, notaMaxima,
                prazo, concluida, dataConclusao, idEstudante); 
    }//GEN-LAST:event_okMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        dispose();
        TelaAtividades tela = new TelaAtividades();
        tela.show();
    }//GEN-LAST:event_voltarMouseClicked

    private void mesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesTextFieldActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovaAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoConclusaoTextField;
    private javax.swing.JTextField anoTextField;
    private javax.swing.JTextField atividadeTextField;
    private javax.swing.JCheckBox concluidaCheckBox;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JTextField diaConclusaoTextField;
    private javax.swing.JTextField diaTextField;
    private javax.swing.JComboBox<String> disciplinasComboBox;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mesConclusaoTextField;
    private javax.swing.JTextField mesTextField;
    private javax.swing.JTextField notaMaxTextField;
    private javax.swing.JTextField notaTextField;
    private javax.swing.JLabel nova;
    private javax.swing.JLabel ok;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
