/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import database.AtividadeDAO;
import database.ConexaoDAO;
import database.EstudanteDAO;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author andre
 */
public class TelaAtividades extends javax.swing.JFrame {
    private EstudanteDAO estudantedao = new EstudanteDAO();
    private AtividadeDAO atividadedao = new AtividadeDAO();


    /**
     * Creates new form TelaAtividades
     */
    public TelaAtividades() {
        initComponents();
    }

    private void obj_btn_startActionPerformed(java.awt.event.ActionEvent evt){
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        novaAtvButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atividadesTabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        descricaoLabel = new javax.swing.JLabel();
        atividadeLabel = new javax.swing.JLabel();
        disciplinaLabel = new javax.swing.JLabel();
        prazoLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        atividadeTextPane = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        disciplinaTextPane = new javax.swing.JTextPane();
        concluidaCheckBox = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        diaConclusaoTextPane = new javax.swing.JTextPane();
        notaLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notaMaxTextPane = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        notaTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        mesConclusaoTextPane = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        anoConclusaoTextPane = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        diaTextPane = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        mesTextPane = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        anoTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tituloLabel.setText("Atividades");

        novaAtvButton.setText("Nova atividade");
        novaAtvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAtvButtonActionPerformed(evt);
            }
        });

        atividadesTabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atividadesTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Atividade", "Disciplina", "Descrição", "Prazo", "Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        atividadesTabela.setRowHeight(30);
        atividadesTabela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                atividadesTabelaFocusGained(evt);
            }
        });
        atividadesTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atividadesTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(atividadesTabela);

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        jScrollPane2.setViewportView(descricaoTextArea);

        descricaoLabel.setText("Descrição");

        atividadeLabel.setText("Atividade");

        disciplinaLabel.setText("Disciplina");

        prazoLabel.setText("Prazo");

        jScrollPane6.setViewportView(atividadeTextPane);

        jScrollPane7.setViewportView(disciplinaTextPane);

        concluidaCheckBox.setText("Concluída");

        jScrollPane8.setViewportView(diaConclusaoTextPane);

        notaLabel.setText("Nota");

        notaMaxTextPane.setText("0.0");
        jScrollPane3.setViewportView(notaMaxTextPane);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.setToolTipText("");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        deletarButton.setText("Deletar");

        jScrollPane4.setToolTipText("");

        notaTextPane.setText("0.0");
        jScrollPane4.setViewportView(notaTextPane);

        jLabel1.setText(" /");

        jScrollPane9.setViewportView(mesConclusaoTextPane);

        jScrollPane10.setViewportView(anoConclusaoTextPane);

        jScrollPane11.setViewportView(diaTextPane);

        jScrollPane12.setViewportView(mesTextPane);

        jScrollPane13.setViewportView(anoTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(tituloLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atividadeLabel)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notaLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(novaAtvButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(descricaoLabel)
                                        .addComponent(disciplinaLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(concluidaCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(prazoLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addComponent(deletarButton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atividadeLabel)
                            .addComponent(notaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disciplinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(descricaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(novaAtvButton)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(concluidaCheckBox)
                                            .addComponent(prazoLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salvarButton)
                                    .addComponent(deletarButton))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novaAtvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAtvButtonActionPerformed
        dispose();
        TelaNovaAtividade tela =new TelaNovaAtividade();
        tela.show();
    }//GEN-LAST:event_novaAtvButtonActionPerformed

    private void atividadesTabelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atividadesTabelaFocusGained
        
    }//GEN-LAST:event_atividadesTabelaFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        String[] col = {"Nome", "Disciplina", "Descrição", "Prazo", "Concluída"};
        
        TelaAtividades tela = new TelaAtividades();
        DefaultTableModel model = (DefaultTableModel) atividadesTabela.getModel();
        atividadesTabela.setModel(model);
        model.setDataVector(atividadedao.formatarTabela(), col);
        
        if (atividadesTabela.getColumnModel().getColumnCount() > 0) {
            atividadesTabela.getColumnModel().getColumn(0).setMinWidth(150);
            atividadesTabela.getColumnModel().getColumn(0).setPreferredWidth(150);
            atividadesTabela.getColumnModel().getColumn(0).setMaxWidth(200);
            atividadesTabela.getColumnModel().getColumn(1).setMinWidth(150);
            atividadesTabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            atividadesTabela.getColumnModel().getColumn(1).setMaxWidth(200);
            atividadesTabela.getColumnModel().getColumn(3).setMinWidth(120);
            atividadesTabela.getColumnModel().getColumn(3).setPreferredWidth(120);
            atividadesTabela.getColumnModel().getColumn(3).setMaxWidth(120);
            atividadesTabela.getColumnModel().getColumn(4).setMinWidth(65);
            atividadesTabela.getColumnModel().getColumn(4).setPreferredWidth(65);
            atividadesTabela.getColumnModel().getColumn(4).setMaxWidth(65);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] col = {"Nome", "Disciplina", "Descrição", "Prazo", "Concluída"};
        
        TelaAtividades tela = new TelaAtividades();
        DefaultTableModel model = (DefaultTableModel) atividadesTabela.getModel();
        atividadesTabela.setModel(model);
        model.setDataVector(atividadedao.formatarTabela(), col);
        
        if (atividadesTabela.getColumnModel().getColumnCount() > 0) {
            atividadesTabela.getColumnModel().getColumn(0).setMinWidth(150);
            atividadesTabela.getColumnModel().getColumn(0).setPreferredWidth(150);
            atividadesTabela.getColumnModel().getColumn(0).setMaxWidth(200);
            atividadesTabela.getColumnModel().getColumn(1).setMinWidth(150);
            atividadesTabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            atividadesTabela.getColumnModel().getColumn(1).setMaxWidth(200);
            atividadesTabela.getColumnModel().getColumn(3).setMinWidth(120);
            atividadesTabela.getColumnModel().getColumn(3).setPreferredWidth(120);
            atividadesTabela.getColumnModel().getColumn(3).setMaxWidth(120);
            atividadesTabela.getColumnModel().getColumn(4).setMinWidth(65);
            atividadesTabela.getColumnModel().getColumn(4).setPreferredWidth(65);
            atividadesTabela.getColumnModel().getColumn(4).setMaxWidth(65);
        }                                        
    }//GEN-LAST:event_formWindowOpened

    private void atividadesTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesTabelaMouseClicked
        int index = atividadesTabela.getSelectedRow();
        atividadeTextPane.setText(AtividadeDAO.atividades.get(index).getNome());
        disciplinaTextPane.setText(AtividadeDAO.atividades.get(index).getNomeDisciplina());
        descricaoTextArea.setText(AtividadeDAO.atividades.get(index).getDescricao());
        concluidaCheckBox.setSelected(AtividadeDAO.atividades.get(index).isConcluida());
        notaMaxTextPane.setText(Double.toString(AtividadeDAO.atividades.get(index).getNotaMax()));
        if(AtividadeDAO.atividades.get(index).isConcluida()){
            notaTextPane.setText(Double.toString(AtividadeDAO.atividades.get(index).getNota()));
            diaConclusaoTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getDataconclusao().getDayOfMonth()));
            mesConclusaoTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getDataconclusao().getMonthValue()));
            anoConclusaoTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getDataconclusao().getYear()));
        }else{
            notaTextPane.setText(Double.toString(AtividadeDAO.atividades.get(index).getNota()));
            diaConclusaoTextPane.setText("");
            mesConclusaoTextPane.setText("");
            anoConclusaoTextPane.setText("");
        }

        diaTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getPrazo().getDayOfMonth()));
        mesTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getPrazo().getMonthValue()));
        anoTextPane.setText(Integer.toString(AtividadeDAO.atividades.get(index).getPrazo().getYear()));
        
                
    }//GEN-LAST:event_atividadesTabelaMouseClicked

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        String nome = atividadeTextPane.getText();
        String descricao = descricaoTextArea.getText();
        double nota = Double.parseDouble(notaTextPane.getText());
        double notaMaxima = Double.parseDouble(notaMaxTextPane.getText());
        boolean concluida = concluidaCheckBox.isSelected();
        LocalDate prazo = LocalDate.of(Integer.parseInt(anoTextPane.getText()),
                Integer.parseInt(mesTextPane.getText()), Integer.parseInt(diaTextPane.getText()));
        LocalDate dataConclusao = LocalDate.of(Integer.parseInt(anoConclusaoTextPane.getText()),
                Integer.parseInt(mesConclusaoTextPane.getText()), Integer.parseInt(diaConclusaoTextPane.getText()));
        int id = AtividadeDAO.atividades.get(atividadesTabela.getSelectedRow()).getId();
        int localId = atividadesTabela.getSelectedRow();
        atividadedao.atualizarAtividade(id, nome, descricao, nota, notaMaxima, concluida, prazo, dataConclusao, localId);
        
    }//GEN-LAST:event_salvarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane anoConclusaoTextPane;
    private javax.swing.JTextPane anoTextPane;
    private javax.swing.JLabel atividadeLabel;
    private javax.swing.JTextPane atividadeTextPane;
    private javax.swing.JTable atividadesTabela;
    private javax.swing.JCheckBox concluidaCheckBox;
    private javax.swing.JButton deletarButton;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JTextPane diaConclusaoTextPane;
    private javax.swing.JTextPane diaTextPane;
    private javax.swing.JLabel disciplinaLabel;
    private javax.swing.JTextPane disciplinaTextPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane mesConclusaoTextPane;
    private javax.swing.JTextPane mesTextPane;
    private javax.swing.JLabel notaLabel;
    private javax.swing.JTextPane notaMaxTextPane;
    private javax.swing.JTextPane notaTextPane;
    private javax.swing.JButton novaAtvButton;
    private javax.swing.JLabel prazoLabel;
    private javax.swing.JButton salvarButton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
