/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import database.ConexaoDAO;
import database.DisciplinaDAO;
import database.EstudanteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class TelaDisciplinas extends javax.swing.JFrame {
    ConexaoDAO conexao = new ConexaoDAO();
    /**
     * Creates new form TelaDisciplinas
     */
    public TelaDisciplinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        disciplinasList = new javax.swing.JList<>();
        novaButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        renomearButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(390, 280));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        disciplinasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(disciplinasList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 200, 110);

        novaButton.setBorderPainted(false);
        novaButton.setContentAreaFilled(false);
        novaButton.setPreferredSize(new java.awt.Dimension(81, 23));
        novaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(novaButton);
        novaButton.setBounds(270, 140, 81, 23);

        deletarButton.setBorderPainted(false);
        deletarButton.setContentAreaFilled(false);
        deletarButton.setPreferredSize(new java.awt.Dimension(81, 23));
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deletarButton);
        deletarButton.setBounds(270, 93, 81, 30);

        renomearButton.setBorderPainted(false);
        renomearButton.setContentAreaFilled(false);
        renomearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renomearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(renomearButton);
        renomearButton.setBounds(270, 53, 80, 30);

        okButton.setBorderPainted(false);
        okButton.setContentAreaFilled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(280, 210, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grupo 69.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 420, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void renomearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renomearButtonActionPerformed
        String antigaDisciplina = disciplinasList.getSelectedValue();
        String novaDisciplina = JOptionPane.showInputDialog("Digite o novo nome da disciplina: ");
        boolean cadastrada = false;
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        if(!DisciplinaDAO.disciplina.isEmpty()){
            for(int i = 0; i < DisciplinaDAO.disciplina.size(); i++){
                if(novaDisciplina.equals(DisciplinaDAO.disciplina.get(i).getNome())){
                    cadastrada = true;
                    break;
                }else{
                    cadastrada = false;
                }
            }
        }
        if(cadastrada){
            JOptionPane.showMessageDialog(null, "Essa disciplina já está cadastrada!", "ERRO!", 0);
            System.out.println("Essa disciplina já está cadastrada!");
        }else{
            conexao.getConnection();
            int id = 0;
            int localId = disciplinasList.getSelectedIndex();
            String query = "SELECT id FROM DISCIPLINA WHERE nome = ? AND fk_estudante = ?";
            ArrayList<Object> dados = new ArrayList<>();
            dados.add(disciplinasList.getSelectedValue()); dados.add(EstudanteDAO.estudante.getId());
            ResultSet rs = conexao.Select(query, dados);
            try{
                if(rs!=null && rs.next()){
                    id = rs.getInt(1);
                }
            }catch(SQLException ex){
                Logger.getLogger(ConexaoDAO.class.getName()).log(Level.SEVERE, null, ex);            
            }
            conexao.closeConnection();
            disciplinadao.atualizarDisciplina(id, novaDisciplina, antigaDisciplina, localId);
        }
        disciplinasList.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarList()));
        
    }//GEN-LAST:event_renomearButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        disciplinasList.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarList()));
    }//GEN-LAST:event_formWindowOpened

    private void novaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaButtonActionPerformed
        String novaDisciplina = JOptionPane.showInputDialog("Digite o nome da disciplina: ");       
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        boolean cadastrada = false;
        if(!DisciplinaDAO.disciplina.isEmpty()){
            for(int i = 0; i < DisciplinaDAO.disciplina.size(); i++){
                if(novaDisciplina.equals(DisciplinaDAO.disciplina.get(i).getNome())){
                    cadastrada = true;
                    break;
                }else{
                    cadastrada = false;
                }
            }
        }
        if(cadastrada){
            JOptionPane.showMessageDialog(null, "Essa disciplina já está cadastrada!", "ERRO!", 0);
            System.out.println("Essa disciplina já está cadastrada!");
        }else{
            disciplinadao.cadastrarDisciplina(novaDisciplina);
        }
        
        disciplinasList.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarList()));
    }//GEN-LAST:event_novaButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        int localId = disciplinasList.getSelectedIndex();
        int id = 0;
        conexao.getConnection();
        String query = "SELECT id FROM DISCIPLINA WHERE nome = ? AND fk_estudante = ?";
        ArrayList<Object> dados = new ArrayList<>();
        dados.add(disciplinasList.getSelectedValue()); dados.add(EstudanteDAO.estudante.getId());
        ResultSet rs = conexao.Select(query, dados);
        try{
            if(rs!=null && rs.next()){
                id = rs.getInt(1);
            }
        }catch(SQLException ex){
            Logger.getLogger(ConexaoDAO.class.getName()).log(Level.SEVERE, null, ex);            
        }  
        conexao.closeConnection();
        disciplinadao.deletarDisciplina(id, localId);
        disciplinasList.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarList()));
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDisciplinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletarButton;
    private javax.swing.JList<String> disciplinasList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novaButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton renomearButton;
    // End of variables declaration//GEN-END:variables
}
