package views;

import javax.swing.table.DefaultTableModel;
import database.ConteudoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaConteudos extends javax.swing.JFrame {

    ConteudoDAO conteudodao = new ConteudoDAO();
    /**
     * Creates new form TelaConteudos
     */
    public TelaConteudos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        conteudosTabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        anotacaoTextPane = new javax.swing.JTextArea();
        escalaSlider = new javax.swing.JSlider();
        escalaLabel = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        conteudoTextField = new javax.swing.JTextField();
        disciplinaTextField = new javax.swing.JTextField();
        revisei = new javax.swing.JLabel();
        revisarLabel = new javax.swing.JLabel();
        deletar = new javax.swing.JLabel();
        salvar = new javax.swing.JLabel();
        novoConteudo = new javax.swing.JLabel();
        atualizar = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        escala = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(702, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        conteudosTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        conteudosTabela.setRowHeight(30);
        conteudosTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conteudosTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(conteudosTabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 350, 530);

        anotacaoTextPane.setColumns(20);
        anotacaoTextPane.setRows(5);
        anotacaoTextPane.setBorder(null);
        jScrollPane2.setViewportView(anotacaoTextPane);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(397, 302, 250, 170);

        escalaSlider.setMaximum(10);
        escalaSlider.setToolTipText("");
        escalaSlider.setValue(5);
        escalaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                escalaSliderStateChanged(evt);
            }
        });
        escalaSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escalaSliderMouseClicked(evt);
            }
        });
        getContentPane().add(escalaSlider);
        escalaSlider.setBounds(380, 150, 300, 26);
        getContentPane().add(escalaLabel);
        escalaLabel.setBounds(910, 160, 15, 0);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(10, 532, 61, 23);

        conteudoTextField.setBorder(null);
        conteudoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conteudoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(conteudoTextField);
        conteudoTextField.setBounds(400, 40, 250, 14);

        disciplinaTextField.setBackground(new java.awt.Color(255, 255, 255));
        disciplinaTextField.setBorder(null);
        disciplinaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(disciplinaTextField);
        disciplinaTextField.setBounds(400, 90, 250, 14);

        revisei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviseiMouseClicked(evt);
            }
        });
        getContentPane().add(revisei);
        revisei.setBounds(390, 200, 100, 30);

        revisarLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        revisarLabel.setForeground(new java.awt.Color(255, 255, 255));
        revisarLabel.setText("jLabel2");
        getContentPane().add(revisarLabel);
        revisarLabel.setBounds(390, 230, 300, 20);

        deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grupo 15.png"))); // NOI18N
        deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarMouseClicked(evt);
            }
        });
        getContentPane().add(deletar);
        deletar.setBounds(390, 490, 110, 30);

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grupo 16.png"))); // NOI18N
        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMouseClicked(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(560, 490, 110, 30);

        novoConteudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoConteudoMouseClicked(evt);
            }
        });
        getContentPane().add(novoConteudo);
        novoConteudo.setBounds(570, 554, 90, 20);

        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(250, 570, 90, 20);

        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(20, 570, 90, 20);

        escala.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        escala.setForeground(new java.awt.Color(255, 255, 255));
        escala.setText("valor");
        getContentPane().add(escala);
        escala.setBounds(640, 180, 28, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conteudos2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void escalaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_escalaSliderStateChanged
        escala.setText(Integer.toString(escalaSlider.getValue()));
    }//GEN-LAST:event_escalaSliderStateChanged

    private void escalaSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escalaSliderMouseClicked
        escala.setText(Integer.toString(escalaSlider.getValue()));
    }//GEN-LAST:event_escalaSliderMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] col = {"Conteúdo", "Disciplina", "Anotações", "Aprendizado"};
        
        TelaAtividades tela = new TelaAtividades();
        DefaultTableModel model = (DefaultTableModel) conteudosTabela.getModel();
        conteudosTabela.setModel(model);
        model.setDataVector(conteudodao.formatarTabela(), col);
        conteudodao.carregarMetas();
        
        if (conteudosTabela.getColumnModel().getColumnCount() > 0) {
            conteudosTabela.getColumnModel().getColumn(0).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(1).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(3).setMinWidth(50);
            conteudosTabela.getColumnModel().getColumn(3).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(3).setMaxWidth(80);
        }

    }//GEN-LAST:event_formWindowOpened

    private void conteudosTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conteudosTabelaMouseClicked
        int index = conteudosTabela.getSelectedRow();
        conteudoTextField.setText(ConteudoDAO.conteudos.get(index).getNome());
        disciplinaTextField.setText(ConteudoDAO.conteudos.get(index).getDisciplina().getNome());
        anotacaoTextPane.setText(ConteudoDAO.conteudos.get(index).getAnotacao());
        escala.setText(Integer.toString(ConteudoDAO.conteudos.get(index).getAprendizado()));
        escalaSlider.setValue(ConteudoDAO.conteudos.get(index).getAprendizado());
        if(ConteudoDAO.conteudos.get(index).getMeta() == 0){
            revisarLabel.setText("Parabéns! Você cumpriu a sua meta!");
        }else{
            revisarLabel.setText("Revisar " + Integer.toString(ConteudoDAO.conteudos.get(index).getMeta()) + " vezes!");
        }
    }//GEN-LAST:event_conteudosTabelaMouseClicked

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose();
        TelaInicial tela = new TelaInicial();
        tela.show();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void reviseiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviseiMouseClicked
        int revisoes = ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getMeta() - 1;
        conteudodao.atualizarMetas(revisoes, conteudosTabela.getSelectedRow());
        if(revisoes == 0){
            JOptionPane.showMessageDialog(null, "Parabéns! Você cumpriu a sua meta!", "Parabéns!", 1);
            revisarLabel.setText("Parabéns! Você cumpriu a sua meta de revisões!");
        }else{
            revisarLabel.setText("Revisar " + Integer.toString(ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getMeta()));
        }    }//GEN-LAST:event_reviseiMouseClicked

    private void deletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarMouseClicked
        int id = ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getId();
        int localId = conteudosTabela.getSelectedRow();
        
        conteudodao.deletarConteudo(id, localId);
    }//GEN-LAST:event_deletarMouseClicked

    private void salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseClicked
        int id = ConteudoDAO.conteudos.get(conteudosTabela.getSelectedRow()).getId();
        String nome = conteudoTextField.getText();
        String anotacao = anotacaoTextPane.getText();
        int aprendizado = escalaSlider.getValue();
        int localId = conteudosTabela.getSelectedRow();
        
        conteudodao.atualizarConteudo(id, nome, anotacao, aprendizado, localId);
        conteudodao.formatarTabela();
    }//GEN-LAST:event_salvarMouseClicked

    private void novoConteudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoConteudoMouseClicked
        dispose();
        TelaNovoConteudo tela = new TelaNovoConteudo();
        tela.show();
    }//GEN-LAST:event_novoConteudoMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        String[] col = {"Conteúdo", "Disciplina", "Anotações", "Aprendizado"};
        
        TelaAtividades tela = new TelaAtividades();
        DefaultTableModel model = (DefaultTableModel) conteudosTabela.getModel();
        conteudosTabela.setModel(model);
        model.setDataVector(conteudodao.formatarTabela(), col);
        conteudodao.carregarMetas();
        
        if (conteudosTabela.getColumnModel().getColumnCount() > 0) {
            conteudosTabela.getColumnModel().getColumn(0).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(0).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(1).setMinWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(1).setMaxWidth(100);
            conteudosTabela.getColumnModel().getColumn(3).setMinWidth(50);
            conteudosTabela.getColumnModel().getColumn(3).setPreferredWidth(80);
            conteudosTabela.getColumnModel().getColumn(3).setMaxWidth(80);
        }
    }//GEN-LAST:event_atualizarMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        dispose();
        TelaInicial tela = new TelaInicial();
        tela.show();
    }//GEN-LAST:event_voltarMouseClicked

    private void disciplinaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinaTextFieldActionPerformed

    private void conteudoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conteudoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conteudoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConteudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConteudos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anotacaoTextPane;
    private javax.swing.JLabel atualizar;
    private javax.swing.JTextField conteudoTextField;
    private javax.swing.JTable conteudosTabela;
    private javax.swing.JLabel deletar;
    private javax.swing.JTextField disciplinaTextField;
    private javax.swing.JLabel escala;
    private javax.swing.JLabel escalaLabel;
    private javax.swing.JSlider escalaSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel novoConteudo;
    private javax.swing.JLabel revisarLabel;
    private javax.swing.JLabel revisei;
    private javax.swing.JLabel salvar;
    private javax.swing.JLabel voltar;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
