
package views;

import database.ConexaoDAO;
import database.DisciplinaDAO;
import database.EstudanteDAO;
import database.ConteudoDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
public class TelaNovoConteudo extends javax.swing.JFrame {
    ConteudoDAO conteudodao = new ConteudoDAO();

    public TelaNovoConteudo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nomeTextPane = new javax.swing.JTextPane();
        disciplinaComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        anotacoesTextArea = new javax.swing.JTextArea();
        aprendizadoSlider = new javax.swing.JSlider();
        okButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        novaDsclpnButton = new javax.swing.JButton();
        aprendizadoSliderLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(nomeTextPane);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 170, 210, 22);

        disciplinaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(disciplinaComboBox);
        disciplinaComboBox.setBounds(360, 170, 140, 20);

        anotacoesTextArea.setColumns(20);
        anotacoesTextArea.setRows(5);
        anotacoesTextArea.setBorder(null);
        anotacoesTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(anotacoesTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 320, 400, 180);

        aprendizadoSlider.setMaximum(10);
        aprendizadoSlider.setValue(5);
        aprendizadoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aprendizadoSliderStateChanged(evt);
            }
        });
        getContentPane().add(aprendizadoSlider);
        aprendizadoSlider.setBounds(80, 240, 420, 26);

        okButton.setBorderPainted(false);
        okButton.setContentAreaFilled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(360, 520, 60, 30);

        voltarButton.setBorderPainted(false);
        voltarButton.setContentAreaFilled(false);
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(150, 520, 60, 30);

        novaDsclpnButton.setBorderPainted(false);
        novaDsclpnButton.setContentAreaFilled(false);
        novaDsclpnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaDsclpnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(novaDsclpnButton);
        novaDsclpnButton.setBounds(390, 200, 70, 20);

        aprendizadoSliderLabel.setText("-");
        getContentPane().add(aprendizadoSliderLabel);
        aprendizadoSliderLabel.setBounds(280, 180, 4, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grupo 73.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 590, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DisciplinaDAO disciplinadao = new DisciplinaDAO();
        disciplinaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinadao.formatarComboBox()));
    }//GEN-LAST:event_formWindowOpened

    private void novaDsclpnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaDsclpnButtonActionPerformed
        TelaDisciplinas tela = new TelaDisciplinas();
        tela.show();
    }//GEN-LAST:event_novaDsclpnButtonActionPerformed

    private void aprendizadoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aprendizadoSliderStateChanged
        aprendizadoSliderLabel.setText(Integer.toString(aprendizadoSlider.getValue()));
    }//GEN-LAST:event_aprendizadoSliderStateChanged

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose();
        TelaConteudos tela = new TelaConteudos();
        tela.show();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String nome = nomeTextPane.getText();
        String anotacao = anotacoesTextArea.getText();
        int aprendizado = aprendizadoSlider.getValue();
        int idDisciplina = 0;
        String querySelect = "SELECT id FROM DISCIPLINA WHERE nome = ? AND fk_estudante = ?";
        ArrayList<Object> dadosSelect = new ArrayList<>();
        dadosSelect.add(disciplinaComboBox.getSelectedItem().toString());
        dadosSelect.add(EstudanteDAO.estudante.getId());
        ConexaoDAO conexao = new ConexaoDAO();
        conexao.getConnection();
        ResultSet rs = conexao.Select(querySelect, dadosSelect);
        try{
            if(rs!= null && rs.next())
                idDisciplina = rs.getInt(1);
        }catch(SQLException ex){
            Logger.getLogger(ConexaoDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        int idEstudante = EstudanteDAO.estudante.getId();
        conexao.closeConnection();
        conteudodao.cadastrarConteudo(nome, anotacao, aprendizado, idDisciplina, idEstudante);

    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoConteudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anotacoesTextArea;
    private javax.swing.JSlider aprendizadoSlider;
    private javax.swing.JLabel aprendizadoSliderLabel;
    private javax.swing.JComboBox<String> disciplinaComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane nomeTextPane;
    private javax.swing.JButton novaDsclpnButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
